name: Dummy GH Action
inputs:
  dummy:
    description: dummy input
    required: true
outputs:
  o:
    description: the dummy out was
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.dummy }}
