name: Example
on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Get Input from py api
      uses: deric4/py-hello-githubactions@master
      id: x
      with:
        dummy: what a dummy

    - name: output
      run: echo "${{ steps.x.outputs.o}}!"
